language: node_js
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#jsbin
before_script:
- npm install
node_js:
- "0.10"
deploy:
  on: master
  api_key:
    secure: Z+jx+RrD8PsrM+BZyzgjE7H5089CvGo8bv9qVLbCRMmGMP91UyP4xenHtQvdtaXiL52tAlWj052jAJCh1ta91+0qjgzSn89WQ4/RGa5OVrmEyiyaVp9fOjHrjGZjb2o/qSQ/cyAuvsS/dDkODYGaDHfePZCk9v55jM9Kj7RxSZc=
  app: jsbin-learn
  provider: heroku